package com.daily.database.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.daily.database.entity.Article;
import com.daily.database.entity.Comment;
import com.daily.database.entity.Section;

import com.daily.database.entity.ArticleDao;
import com.daily.database.entity.CommentDao;
import com.daily.database.entity.SectionDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig sectionDaoConfig;

    private final ArticleDao articleDao;
    private final CommentDao commentDao;
    private final SectionDao sectionDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        sectionDaoConfig = daoConfigMap.get(SectionDao.class).clone();
        sectionDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        sectionDao = new SectionDao(sectionDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Comment.class, commentDao);
        registerDao(Section.class, sectionDao);
    }
    
    public void clear() {
        articleDaoConfig.clearIdentityScope();
        commentDaoConfig.clearIdentityScope();
        sectionDaoConfig.clearIdentityScope();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public SectionDao getSectionDao() {
        return sectionDao;
    }

}
